/* Generated by Yosys 0.19+42 (git sha1 7d4f87d69f0, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module iiitb_elc(request_floor, in_current_floor, clk, reset, complete, direction, over_time, over_weight, weight_alert, door_alert, out_current_floor);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  input clk;
  wire clk;
  output complete;
  wire complete;
  output direction;
  wire direction;
  output door_alert;
  wire door_alert;
  input [7:0] in_current_floor;
  wire [7:0] in_current_floor;
  output [7:0] out_current_floor;
  wire [7:0] out_current_floor;
  input over_time;
  wire over_time;
  input over_weight;
  wire over_weight;
  wire r_complete;
  wire r_direction;
  wire r_door_alert;
  wire [7:0] r_out_current_floor;
  wire r_weight_alert;
  input [7:0] request_floor;
  wire [7:0] request_floor;
  input reset;
  wire reset;
  output weight_alert;
  wire weight_alert;
  sky130_fd_sc_hd__clkinv_1 _107_ (
    .A(reset),
    .Y(_048_)
  );
  sky130_fd_sc_hd__clkinv_1 _108_ (
    .A(r_out_current_floor[7]),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nand2_1 _109_ (
    .A(_049_),
    .B(request_floor[7]),
    .Y(_050_)
  );
  sky130_fd_sc_hd__clkinv_1 _110_ (
    .A(r_out_current_floor[6]),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nand2_1 _111_ (
    .A(_051_),
    .B(request_floor[6]),
    .Y(_052_)
  );
  sky130_fd_sc_hd__clkinv_1 _112_ (
    .A(request_floor[7]),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nand2_1 _113_ (
    .A(_053_),
    .B(r_out_current_floor[7]),
    .Y(_054_)
  );
  sky130_fd_sc_hd__clkinv_1 _114_ (
    .A(request_floor[6]),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nand2_1 _115_ (
    .A(_055_),
    .B(r_out_current_floor[6]),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nand4_1 _116_ (
    .A(_050_),
    .B(_052_),
    .C(_054_),
    .D(_056_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__clkinv_1 _117_ (
    .A(r_out_current_floor[5]),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nand2_1 _118_ (
    .A(_058_),
    .B(request_floor[5]),
    .Y(_059_)
  );
  sky130_fd_sc_hd__clkinv_1 _119_ (
    .A(r_out_current_floor[4]),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nand2_1 _120_ (
    .A(_060_),
    .B(request_floor[4]),
    .Y(_061_)
  );
  sky130_fd_sc_hd__clkinv_1 _121_ (
    .A(request_floor[5]),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nand2_1 _122_ (
    .A(_062_),
    .B(r_out_current_floor[5]),
    .Y(_063_)
  );
  sky130_fd_sc_hd__clkinv_1 _123_ (
    .A(request_floor[4]),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nand2_1 _124_ (
    .A(_064_),
    .B(r_out_current_floor[4]),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nand4_1 _125_ (
    .A(_059_),
    .B(_061_),
    .C(_063_),
    .D(_065_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nor2_1 _126_ (
    .A(_057_),
    .B(_066_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__clkinv_1 _127_ (
    .A(r_out_current_floor[3]),
    .Y(_068_)
  );
  sky130_fd_sc_hd__clkinv_1 _128_ (
    .A(r_out_current_floor[2]),
    .Y(_069_)
  );
  sky130_fd_sc_hd__a22oi_1 _129_ (
    .A1(_068_),
    .A2(request_floor[3]),
    .B1(_069_),
    .B2(request_floor[2]),
    .Y(_070_)
  );
  sky130_fd_sc_hd__or2b_2 _130_ (
    .A(request_floor[3]),
    .B_N(r_out_current_floor[3]),
    .X(_071_)
  );
  sky130_fd_sc_hd__or2b_2 _131_ (
    .A(request_floor[2]),
    .B_N(r_out_current_floor[2]),
    .X(_072_)
  );
  sky130_fd_sc_hd__and3_2 _132_ (
    .A(_070_),
    .B(_071_),
    .C(_072_),
    .X(_073_)
  );
  sky130_fd_sc_hd__clkinv_1 _133_ (
    .A(request_floor[1]),
    .Y(_074_)
  );
  sky130_fd_sc_hd__clkinv_1 _134_ (
    .A(request_floor[0]),
    .Y(_075_)
  );
  sky130_fd_sc_hd__a22oi_1 _135_ (
    .A1(_074_),
    .A2(r_out_current_floor[1]),
    .B1(_075_),
    .B2(r_out_current_floor[0]),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nor2_1 _136_ (
    .A(r_out_current_floor[0]),
    .B(_075_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nor2_1 _137_ (
    .A(r_out_current_floor[1]),
    .B(_074_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nor2_1 _138_ (
    .A(_077_),
    .B(_078_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nand4_1 _139_ (
    .A(_067_),
    .B(_073_),
    .C(_076_),
    .D(_079_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__clkinv_1 _140_ (
    .A(_071_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nand2_1 _141_ (
    .A(_068_),
    .B(request_floor[3]),
    .Y(_082_)
  );
  sky130_fd_sc_hd__nand2_1 _142_ (
    .A(_069_),
    .B(request_floor[2]),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nand4_1 _143_ (
    .A(_082_),
    .B(_083_),
    .C(_071_),
    .D(_072_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nand2_1 _144_ (
    .A(_075_),
    .B(r_out_current_floor[0]),
    .Y(_085_)
  );
  sky130_fd_sc_hd__or2b_2 _145_ (
    .A(request_floor[1]),
    .B_N(r_out_current_floor[1]),
    .X(_086_)
  );
  sky130_fd_sc_hd__a21oi_1 _146_ (
    .A1(_085_),
    .A2(_086_),
    .B1(_078_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__o22ai_1 _147_ (
    .A1(_070_),
    .A2(_081_),
    .B1(_084_),
    .B2(_087_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__nand2_1 _148_ (
    .A(_088_),
    .B(_067_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__a22oi_1 _149_ (
    .A1(_049_),
    .A2(request_floor[7]),
    .B1(_051_),
    .B2(request_floor[6]),
    .Y(_090_)
  );
  sky130_fd_sc_hd__nor2_1 _150_ (
    .A(request_floor[7]),
    .B(_049_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__nand2_1 _151_ (
    .A(_059_),
    .B(_061_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nand2_1 _152_ (
    .A(_092_),
    .B(_063_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__o22a_2 _153_ (
    .A1(_090_),
    .A2(_091_),
    .B1(_057_),
    .B2(_093_),
    .X(_094_)
  );
  sky130_fd_sc_hd__nand2_1 _154_ (
    .A(_089_),
    .B(_094_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nand2_1 _155_ (
    .A(_095_),
    .B(_080_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nand3_1 _156_ (
    .A(_096_),
    .B(_048_),
    .C(r_out_current_floor[1]),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nor2_1 _157_ (
    .A(over_time),
    .B(over_weight),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nor2_1 _158_ (
    .A(reset),
    .B(_098_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__clkinv_1 _159_ (
    .A(_099_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__o21ai_0 _160_ (
    .A1(reset),
    .A2(_080_),
    .B1(_100_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__clkinv_1 _161_ (
    .A(_101_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__a21oi_1 _162_ (
    .A1(reset),
    .A2(in_current_floor[0]),
    .B1(_101_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__a2bb2oi_1 _163_ (
    .A1_N(r_out_current_floor[0]),
    .A2_N(_102_),
    .B1(_097_),
    .B2(_103_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__clkinv_1 _164_ (
    .A(r_out_current_floor[1]),
    .Y(_104_)
  );
  sky130_fd_sc_hd__o21a_1 _165_ (
    .A1(_069_),
    .A2(request_floor[2]),
    .B1(_071_),
    .X(_105_)
  );
  sky130_fd_sc_hd__nand4_1 _166_ (
    .A(_079_),
    .B(_105_),
    .C(_070_),
    .D(_076_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__nor3_1 _167_ (
    .A(_057_),
    .B(_066_),
    .C(_106_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__o22ai_1 _168_ (
    .A1(_090_),
    .A2(_091_),
    .B1(_057_),
    .B2(_093_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__a21oi_1 _169_ (
    .A1(_088_),
    .A2(_067_),
    .B1(_013_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__o21bai_1 _170_ (
    .A1(_012_),
    .A2(_014_),
    .B1_N(_069_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__nand3_1 _171_ (
    .A(_095_),
    .B(r_out_current_floor[0]),
    .C(_080_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nand3_1 _172_ (
    .A(_015_),
    .B(_016_),
    .C(_048_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nor2_1 _173_ (
    .A(in_current_floor[1]),
    .B(_048_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nor2_1 _174_ (
    .A(_018_),
    .B(_101_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _175_ (
    .A1_N(_019_),
    .A2_N(_017_),
    .B1(_104_),
    .B2(_102_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__o21bai_1 _176_ (
    .A1(_012_),
    .A2(_014_),
    .B1_N(_068_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nand3_1 _177_ (
    .A(_095_),
    .B(r_out_current_floor[1]),
    .C(_080_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nand3_1 _178_ (
    .A(_020_),
    .B(_021_),
    .C(_048_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nor2_1 _179_ (
    .A(in_current_floor[2]),
    .B(_048_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nor2_1 _180_ (
    .A(_023_),
    .B(_101_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _181_ (
    .A1_N(_024_),
    .A2_N(_022_),
    .B1(_069_),
    .B2(_102_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__o21bai_1 _182_ (
    .A1(_012_),
    .A2(_014_),
    .B1_N(_060_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nand3_1 _183_ (
    .A(_095_),
    .B(r_out_current_floor[2]),
    .C(_080_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nand3_1 _184_ (
    .A(_025_),
    .B(_026_),
    .C(_048_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__nor2_1 _185_ (
    .A(in_current_floor[3]),
    .B(_048_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nor2_1 _186_ (
    .A(_028_),
    .B(_101_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _187_ (
    .A1_N(_029_),
    .A2_N(_027_),
    .B1(_068_),
    .B2(_102_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__o21bai_1 _188_ (
    .A1(_012_),
    .A2(_014_),
    .B1_N(_058_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nand3_1 _189_ (
    .A(_095_),
    .B(r_out_current_floor[3]),
    .C(_080_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nand3_1 _190_ (
    .A(_030_),
    .B(_031_),
    .C(_048_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nor2_1 _191_ (
    .A(in_current_floor[4]),
    .B(_048_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nor2_1 _192_ (
    .A(_033_),
    .B(_101_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _193_ (
    .A1_N(_034_),
    .A2_N(_032_),
    .B1(_060_),
    .B2(_102_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__o21bai_1 _194_ (
    .A1(_012_),
    .A2(_014_),
    .B1_N(_051_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nand3_1 _195_ (
    .A(_095_),
    .B(r_out_current_floor[4]),
    .C(_080_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nand3_1 _196_ (
    .A(_035_),
    .B(_036_),
    .C(_048_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nor2_1 _197_ (
    .A(in_current_floor[5]),
    .B(_048_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__nor2_1 _198_ (
    .A(_038_),
    .B(_101_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _199_ (
    .A1_N(_039_),
    .A2_N(_037_),
    .B1(_058_),
    .B2(_102_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__o21bai_1 _200_ (
    .A1(_012_),
    .A2(_014_),
    .B1_N(_049_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__nand3_1 _201_ (
    .A(_095_),
    .B(r_out_current_floor[5]),
    .C(_080_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__nand3_1 _202_ (
    .A(_040_),
    .B(_041_),
    .C(_048_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nor2_1 _203_ (
    .A(in_current_floor[6]),
    .B(_048_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nor2_1 _204_ (
    .A(_043_),
    .B(_101_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _205_ (
    .A1_N(_044_),
    .A2_N(_042_),
    .B1(_051_),
    .B2(_102_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nand4_1 _206_ (
    .A(_095_),
    .B(_048_),
    .C(r_out_current_floor[6]),
    .D(_080_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__a21oi_1 _207_ (
    .A1(reset),
    .A2(in_current_floor[7]),
    .B1(_101_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__a22oi_1 _208_ (
    .A1(_049_),
    .A2(_101_),
    .B1(_046_),
    .B2(_045_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__a21oi_1 _209_ (
    .A1(_096_),
    .A2(_048_),
    .B1(_099_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__nor4_1 _210_ (
    .A(over_time),
    .B(reset),
    .C(over_weight),
    .D(_080_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__clkinv_1 _211_ (
    .A(over_time),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nor2_1 _212_ (
    .A(reset),
    .B(_047_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nor2_1 _213_ (
    .A(over_time),
    .B(_100_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__dfxtp_1 _214_ (
    .CLK(clk),
    .D(_000_),
    .Q(r_out_current_floor[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _215_ (
    .CLK(clk),
    .D(_001_),
    .Q(r_out_current_floor[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _216_ (
    .CLK(clk),
    .D(_002_),
    .Q(r_out_current_floor[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _217_ (
    .CLK(clk),
    .D(_003_),
    .Q(r_out_current_floor[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _218_ (
    .CLK(clk),
    .D(_004_),
    .Q(r_out_current_floor[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _219_ (
    .CLK(clk),
    .D(_005_),
    .Q(r_out_current_floor[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _220_ (
    .CLK(clk),
    .D(_006_),
    .Q(r_out_current_floor[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _221_ (
    .CLK(clk),
    .D(_007_),
    .Q(r_out_current_floor[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _222_ (
    .CLK(clk),
    .D(_008_),
    .Q(r_direction)
  );
  sky130_fd_sc_hd__dfxtp_1 _223_ (
    .CLK(clk),
    .D(_009_),
    .Q(r_complete)
  );
  sky130_fd_sc_hd__dfxtp_1 _224_ (
    .CLK(clk),
    .D(_010_),
    .Q(r_door_alert)
  );
  sky130_fd_sc_hd__dfxtp_1 _225_ (
    .CLK(clk),
    .D(_011_),
    .Q(r_weight_alert)
  );
  assign complete = r_complete;
  assign direction = r_direction;
  assign door_alert = r_door_alert;
  assign out_current_floor = r_out_current_floor;
  assign weight_alert = r_weight_alert;
endmodule
